Drcandacemakedamoore/mri episode
esciencecenter-digital-skills/medical-image-processing pull request #11
Opened 2024-05-06 01:51 UTC by drcandacemakedamoore

This is the MRI episode, with one tweak to the previous (intro to images) episode.

2024-05-17 14:54 UTC, gcroci2 requested changes
Great lesson :)

I added some suggestions and fixed some typos in https://github.com/esciencecenter-digital-skills/medical-image-processing/pull/11/commits/cdf54db4918a851dc7f9d3fc6006d704f499a844, feel free to revert it or editing the file further. 

A note on the images: I don't see any in the fig/ folder (t1t2flairbrain.jpg, bold.gif, etc.), so I am not sure how they were able to be rendered on my local machine, but they did. I guess that they should be uploaded in the repository for being rendered on the online website, right? Same for the images in the first lesson (introduction_to_medical_imaging.md). If you look carefully indeed, you can see in "Files changes" that the bot gives many missing file warnings in both episodes.

2024-05-20 15:49 UTC, drcandacemakedamoore commented
I accept your changes. I am going to add one more change in an upcoming commit based on new conversations with a neuroimaging specialist. Please make sure you accept or request changes on this as well, @gcroci2  then it should be good to approve, I hope.

2024-05-21 13:52 UTC, drcandacemakedamoore commented
@gcroci2 your final changes are fine. I'm not sure what happened to the files, so I just added them back in, but also the new ones for your SITK episode- so it's all there now, or should be. If you want to pull off the SITK ones, go ahead, but otherwise, this should now be good to get approved, rebase and merge, I think.

2024-05-21 15:15 UTC, gcroci2 commented
> @gcroci2 your final changes are fine. I'm not sure what happened to the files, so I just added them back in, but also the new ones for your SITK episode- so it's all there now, or should be. If you want to pull off the SITK ones, go ahead, but otherwise, this should now be good to get approved, rebase and merge, I think.

Please remove the SITK ones, they are in my PR, no need to have them here, then I'll do a last check and we can merge :) @drcandacemakedamoore

2024-05-21 15:36 UTC, drcandacemakedamoore commented
@gcroci2 I pulled off the images, but I'm highly pedantic and OCD about using rebase and merge over a plain merge, so unless it bothers you I will rebase and merge.

2024-05-23 15:16 UTC, gcroci2 commented
All images almost there :) these still missing from episodes/fig folder: `fmri_timeseries.png`, `numpy_arrays.png`, `mri_slices.jpg` @drcandacemakedamoore tag me again when you've added them, I will double check to be sure and then I'll finally approve!

2024-05-23 15:19 UTC, drcandacemakedamoore commented
@gcroci2 They are there, I see them in the diff files

2024-05-23 15:20 UTC, gcroci2 approved these changes

2024-05-23 15:21 UTC, gcroci2 commented
> @gcroci2 They are there, I see them in the diff files

My bad, just approved :)

2024-05-23 19:26 UTC, merged

2024-05-24 08:25 UTC, gcroci2 commented
Why did you add here all the sitk PR's commits? @drcandacemakedamoore

2024-05-24 08:32 UTC, gcroci2 commented on episodes/simpleitk.md
> +## Acknowledgements
This is repeated twice, not sure what happened but I see you added this section @drcandacemakedamoore

2024-05-25 12:57 UTC, drcandacemakedamoore commented
Because I rebased on the SITK branch, as they had conflicts ( the config
file and old SITK episode).

On Fri, May 24, 2024, 10:32 AM Giulia Crocioni ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In episodes/simpleitk.md
> <https://github.com/esciencecenter-digital-skills/medical-image-processing/pull/11#discussion_r1613089365>
> :
>
> > @@ -935,6 +935,10 @@ TBD
>
>  This episode was largely inspired by [the official SITK tutorial](https://simpleitk.org/TUTORIAL/#tutorial), which is copyrighted by NumFOCUS and distributed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
>
> +## Acknowledgements
>
> This is repeated twice, not sure what happened but I see you added this
> section @drcandacemakedamoore <https://github.com/drcandacemakedamoore>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esciencecenter-digital-skills/medical-image-processing/pull/11#pullrequestreview-2076231557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHMYSAKVWYBB43ESFVJ72P3ZD33KXAVCNFSM6AAAAABHIHC472VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZWGIZTCNJVG4>
> .
> You are receiving this because you were mentioned.Message ID:
> <esciencecenter-digital-skills/medical-image-processing/pull/11/review/2076231557
> @github.com>
>

2024-05-27 07:24 UTC, gcroci2 commented
> Because I rebased on the SITK branch, as they had conflicts ( the config file and old SITK episode).

But the SITK branch was already merged into main, so I don't get why this was actually needed. Maybe next time let's do the rebase and merge together, to be sure the flow is clear to both of us (now it's not to me) @drcandacemakedamoore