section 3: registration and segmentation with SITK
esciencecenter-digital-skills/medical-image-processing pull request #12
Opened 2024-05-06 09:01 UTC by gcroci2

2024-05-06 16:22 UTC, drcandacemakedamoore commented
For an outline this looks good, but did you put this PR up as a draft, or is it really to be approved by me before moving forward?

2024-05-10 11:55 UTC, gcroci2 commented
> For an outline this looks good, but did you put this PR up as a draft, or is it really to be approved by me before moving forward?

I will ask for your review when the PR is ready :) getting there!

2024-05-16 12:39 UTC, drcandacemakedamoore commented
We should add a bell-box about different approaches to registration to highlight that it can be done with dipy (which is mentioned in the MRI episode) in very specific ways on diffusion imaging e.g. SymmetricDiffeomorphicRegistration functionality, or even bare(r) python. We must warn people to pick one system (for diffusion imaging go with dipy and for many other things go with SITK) so they don't create confusion.

2024-05-16 15:12 UTC, gcroci2 commented
> We should add a bell-box about different approaches to registration to highlight that it can be done with dipy (which is mentioned in the MRI episode) in very specific ways on diffusion imaging e.g. SymmetricDiffeomorphicRegistration functionality, or even bare(r) python. We must warn people to pick one system (for diffusion imaging go with dipy and for many other things go with SITK) so they don't create confusion. Also there is the same kind of issue with using SITK GetMetaDataKeys versus just using PyDICOM. Maybe we can have two bell boxes, or we can have one saying there is more than one way to skin a cat.

Makes sense! Maybe you can directly add a commit on this branch with it (or a scratch of it to guide me)? I think you know better what you mean and it seems to me that your vision on the table is already pretty clear :) @drcandacemakedamoore

2024-05-16 17:33 UTC, drcandacemakedamoore requested changes
There are some comments to consider I have placed . The main issue is that the code at the point indicated stops my kernel. Please go ahead and make a conda-environment file, so I can consider if this is related to my environment in some way. If you run your cells top to bottom, if your kernel intact?

2024-05-16 17:33 UTC, drcandacemakedamoore commented on episodes/simpleitk.md
> +There are a variety of level-set based segmentation filter available in ITK:
What is missing here is a sentence to tell me what level set segmentation means. I still have only a vague idea that it has something to do with topology. If it's too complicated to explain, maybe a link to a paper or textbook.

2024-05-20 18:33 UTC, drcandacemakedamoore commented
@gcroci2 I added the bell boxes.in a new commit ([12ceeb0](https://github.com/esciencecenter-digital-skills/medical-image-processing/pull/12/commits/12ceeb06f574e10351d813b661a8d13cfde60dbf)).  Feel free to change them a bit.

2024-05-21 08:25 UTC, gcroci2 commented on episodes/simpleitk.md
> +```
I rerun the code and it doesn't break for me :)

2024-05-21 08:28 UTC, gcroci2 commented
Thanks for the suggestions, I added them :) @drcandacemakedamoore 

As I answered above, the code does not break for me. I don't have anything special in my env, only sitk and numpy installed, and I am using python 3.10.

2024-05-23 14:53 UTC, drcandacemakedamoore approved these changes

2024-05-23 14:54 UTC, merged