Drcandacemakedamoore/update glossary
esciencecenter-digital-skills/medical-image-processing pull request #24
Opened 2024-07-21 09:56 UTC by drcandacemakedamoore

We can survey the pilot participants for what additonal terms are important to them.

2024-08-01 11:48 UTC, gcroci2 requested changes
Thanks for having updated it. This will be very useful for the students! 

I think that this PR is blocked by #6 (PR #16), and eventually #4 - if we are going to develop it, which may be no more the case. Once all the lessons are merged into main, we should go through them and check whether all the mainly needed terms have been added here. I moved the issue (#14) to the In Progess column because of this reason.

2024-08-14 12:22 UTC, gcroci2 approved these changes

2024-08-14 12:22 UTC, gcroci2 commented
I added few terms to have a more complete (but still starting) glossary. If you approve them, feel free to merge the PR :) @drcandacemakedamoore

2024-08-15 04:27 UTC, drcandacemakedamoore commented
I put a slight tweak onto the radiomics definition. Otherwise fine

2024-08-15 04:27 UTC, merged